INSUMOS = [
    {"id_insumo": "INS-001", "nome": "Carne Moída", "categoria_insumo": "Carnes", "unidade_compra": "kg", "preco_unitario": 32.90},
    {"id_insumo": "INS-002", "nome": "Frango Desfiado", "categoria_insumo": "Carnes", "unidade_compra": "kg", "preco_unitario": 18.50},
    {"id_insumo": "INS-003", "nome": "Bacon", "categoria_insumo": "Carnes", "unidade_compra": "kg", "preco_unitario": 28.00},
    {"id_insumo": "INS-004", "nome": "Calabresa", "categoria_insumo": "Carnes", "unidade_compra": "kg", "preco_unitario": 22.00},
    {"id_insumo": "INS-005", "nome": "Peito de Frango", "categoria_insumo": "Carnes", "unidade_compra": "kg", "preco_unitario": 16.90},
    {"id_insumo": "INS-006", "nome": "Coxa de Frango", "categoria_insumo": "Carnes", "unidade_compra": "kg", "preco_unitario": 12.50},
    {"id_insumo": "INS-007", "nome": "Carne de Porco", "categoria_insumo": "Carnes", "unidade_compra": "kg", "preco_unitario": 24.00},
    {"id_insumo": "INS-008", "nome": "Linguiça Toscana", "categoria_insumo": "Carnes", "unidade_compra": "kg", "preco_unitario": 19.90},
    {"id_insumo": "INS-009", "nome": "Queijo Mussarela", "categoria_insumo": "Frios", "unidade_compra": "kg", "preco_unitario": 30.00},
    {"id_insumo": "INS-010", "nome": "Queijo Prato", "categoria_insumo": "Frios", "unidade_compra": "kg", "preco_unitario": 28.00},
    {"id_insumo": "INS-011", "nome": "Presunto", "categoria_insumo": "Frios", "unidade_compra": "kg", "preco_unitario": 25.00},
    {"id_insumo": "INS-012", "nome": "Mortadela", "categoria_insumo": "Frios", "unidade_compra": "kg", "preco_unitario": 18.00},
    {"id_insumo": "INS-013", "nome": "Salame", "categoria_insumo": "Frios", "unidade_compra": "kg", "preco_unitario": 35.00},
    {"id_insumo": "INS-014", "nome": "Queijo Parmesão", "categoria_insumo": "Frios", "unidade_compra": "kg", "preco_unitario": 45.00},
    {"id_insumo": "INS-015", "nome": "Pão de Hambúrguer", "categoria_insumo": "Padaria", "unidade_compra": "un", "preco_unitario": 0.80},
    {"id_insumo": "INS-016", "nome": "Pão Francês", "categoria_insumo": "Padaria", "unidade_compra": "un", "preco_unitario": 0.50},
    {"id_insumo": "INS-017", "nome": "Pão Brioche", "categoria_insumo": "Padaria", "unidade_compra": "un", "preco_unitario": 1.20},
    {"id_insumo": "INS-018", "nome": "Pão Integral", "categoria_insumo": "Padaria", "unidade_compra": "un", "preco_unitario": 0.90},
    {"id_insumo": "INS-019", "nome": "Pão de Forma", "categoria_insumo": "Padaria", "unidade_compra": "un", "preco_unitario": 4.50},
    {"id_insumo": "INS-020", "nome": "Alface", "categoria_insumo": "Vegetais", "unidade_compra": "kg", "preco_unitario": 10.00},
    {"id_insumo": "INS-021", "nome": "Tomate", "categoria_insumo": "Vegetais", "unidade_compra": "kg", "preco_unitario": 8.00},
    {"id_insumo": "INS-022", "nome": "Cebola", "categoria_insumo": "Vegetais", "unidade_compra": "kg", "preco_unitario": 5.00},
    {"id_insumo": "INS-023", "nome": "Alho", "categoria_insumo": "Vegetais", "unidade_compra": "kg", "preco_unitario": 12.00},
    {"id_insumo": "INS-024", "nome": "Batata", "categoria_insumo": "Vegetais", "unidade_compra": "kg", "preco_unitario": 4.50},
    {"id_insumo": "INS-025", "nome": "Batata Palha", "categoria_insumo": "Vegetais", "unidade_compra": "kg", "preco_unitario": 15.00},
    {"id_insumo": "INS-026", "nome": "Cenoura", "categoria_insumo": "Vegetais", "unidade_compra": "kg", "preco_unitario": 6.00},
    {"id_insumo": "INS-027", "nome": "Pimentão", "categoria_insumo": "Vegetais", "unidade_compra": "kg", "preco_unitario": 7.50},
    {"id_insumo": "INS-028", "nome": "Ketchup", "categoria_insumo": "Molhos", "unidade_compra": "L", "preco_unitario": 12.00},
    {"id_insumo": "INS-029", "nome": "Maionese", "categoria_insumo": "Molhos", "unidade_compra": "L", "preco_unitario": 14.00},
    {"id_insumo": "INS-030", "nome": "Mostarda", "categoria_insumo": "Molhos", "unidade_compra": "L", "preco_unitario": 11.00},
    {"id_insumo": "INS-031", "nome": "Molho Especial", "categoria_insumo": "Molhos", "unidade_compra": "L", "preco_unitario": 18.00},
    {"id_insumo": "INS-032", "nome": "Molho Barbecue", "categoria_insumo": "Molhos", "unidade_compra": "L", "preco_unitario": 16.00},
    {"id_insumo": "INS-033", "nome": "Molho de Alho", "categoria_insumo": "Molhos", "unidade_compra": "L", "preco_unitario": 15.00},
    {"id_insumo": "INS-034", "nome": "Molho de Pimenta", "categoria_insumo": "Molhos", "unidade_compra": "L", "preco_unitario": 20.00},
    {"id_insumo": "INS-035", "nome": "Sal", "categoria_insumo": "Temperos", "unidade_compra": "kg", "preco_unitario": 2.50},
    {"id_insumo": "INS-036", "nome": "Pimenta do Reino", "categoria_insumo": "Temperos", "unidade_compra": "kg", "preco_unitario": 35.00},
    {"id_insumo": "INS-037", "nome": "Orégano", "categoria_insumo": "Temperos", "unidade_compra": "kg", "preco_unitario": 28.00},
    {"id_insumo": "INS-038", "nome": "Açafrão", "categoria_insumo": "Temperos", "unidade_compra": "kg", "preco_unitario": 40.00},
    {"id_insumo": "INS-039", "nome": "Páprica", "categoria_insumo": "Temperos", "unidade_compra": "kg", "preco_unitario": 25.00},
    {"id_insumo": "INS-040", "nome": "Cominho", "categoria_insumo": "Temperos", "unidade_compra": "kg", "preco_unitario": 22.00},
    {"id_insumo": "INS-041", "nome": "Leite", "categoria_insumo": "Laticínios", "unidade_compra": "L", "preco_unitario": 5.00},
    {"id_insumo": "INS-042", "nome": "Creme de Leite", "categoria_insumo": "Laticínios", "unidade_compra": "L", "preco_unitario": 12.00},
    {"id_insumo": "INS-043", "nome": "Manteiga", "categoria_insumo": "Laticínios", "unidade_compra": "kg", "preco_unitario": 25.00},
    {"id_insumo": "INS-044", "nome": "Iogurte", "categoria_insumo": "Laticínios", "unidade_compra": "L", "preco_unitario": 8.00},
    {"id_insumo": "INS-045", "nome": "Óleo de Soja", "categoria_insumo": "Óleos", "unidade_compra": "L", "preco_unitario": 8.00},
    {"id_insumo": "INS-046", "nome": "Azeite", "categoria_insumo": "Óleos", "unidade_compra": "L", "preco_unitario": 35.00},
    {"id_insumo": "INS-047", "nome": "Farinha de Trigo", "categoria_insumo": "Farináceos", "unidade_compra": "kg", "preco_unitario": 4.50},
    {"id_insumo": "INS-048", "nome": "Pão Ralado", "categoria_insumo": "Farináceos", "unidade_compra": "kg", "preco_unitario": 8.00},
    {"id_insumo": "INS-049", "nome": "Fubá", "categoria_insumo": "Farináceos", "unidade_compra": "kg", "preco_unitario": 5.00},
    {"id_insumo": "INS-050", "nome": "Arroz", "categoria_insumo": "Grãos", "unidade_compra": "kg", "preco_unitario": 6.00},
    {"id_insumo": "INS-051", "nome": "Feijão", "categoria_insumo": "Grãos", "unidade_compra": "kg", "preco_unitario": 8.00},
    {"id_insumo": "INS-052", "nome": "Lentilha", "categoria_insumo": "Grãos", "unidade_compra": "kg", "preco_unitario": 9.00},
    {"id_insumo": "INS-053", "nome": "Salsicha", "categoria_insumo": "Embutidos", "unidade_compra": "kg", "preco_unitario": 15.00},
    {"id_insumo": "INS-054", "nome": "Linguiça", "categoria_insumo": "Embutidos", "unidade_compra": "kg", "preco_unitario": 18.00},
    {"id_insumo": "INS-055", "nome": "Refrigerante", "categoria_insumo": "Bebidas", "unidade_compra": "L", "preco_unitario": 5.00},
    {"id_insumo": "INS-056", "nome": "Suco Natural", "categoria_insumo": "Bebidas", "unidade_compra": "L", "preco_unitario": 7.00},
    {"id_insumo": "INS-057", "nome": "Água", "categoria_insumo": "Bebidas", "unidade_compra": "L", "preco_unitario": 2.00},
    {"id_insumo": "INS-058", "nome": "Cerveja", "categoria_insumo": "Bebidas", "unidade_compra": "L", "preco_unitario": 8.00},
    {"id_insumo": "INS-059", "nome": "Ovo", "categoria_insumo": "Carnes", "unidade_compra": "un", "preco_unitario": 1.20},
    {"id_insumo": "INS-060", "nome": "Macarrão", "categoria_insumo": "Farináceos", "unidade_compra": "kg", "preco_unitario": 6.50},
    {"id_insumo": "INS-061", "nome": "Molho Bolonhesa", "categoria_insumo": "Molhos", "unidade_compra": "L", "preco_unitario": 15.00},
    {"id_insumo": "INS-062", "nome": "Frango Empanado", "categoria_insumo": "Carnes", "unidade_compra": "kg", "preco_unitario": 20.00},
    {"id_insumo": "INS-063", "nome": "Picanha", "categoria_insumo": "Carnes", "unidade_compra": "kg", "preco_unitario": 55.00},
    {"id_insumo": "INS-064", "nome": "Filé de Peixe", "categoria_insumo": "Carnes", "unidade_compra": "kg", "preco_unitario": 35.00},
    {"id_insumo": "INS-065", "nome": "Sorvete", "categoria_insumo": "Laticínios", "unidade_compra": "L", "preco_unitario": 18.00},
    {"id_insumo": "INS-066", "nome": "Calda de Chocolate", "categoria_insumo": "Molhos", "unidade_compra": "L", "preco_unitario": 12.00},
    {"id_insumo": "INS-067", "nome": "Calda de Morango", "categoria_insumo": "Molhos", "unidade_compra": "L", "preco_unitario": 12.00},
    {"id_insumo": "INS-068", "nome": "Leite Condensado", "categoria_insumo": "Laticínios", "unidade_compra": "L", "preco_unitario": 8.00},
    {"id_insumo": "INS-069", "nome": "Milkshake Mix", "categoria_insumo": "Bebidas", "unidade_compra": "L", "preco_unitario": 10.00},
    {"id_insumo": "INS-070", "nome": "Croutons", "categoria_insumo": "Farináceos", "unidade_compra": "kg", "preco_unitario": 12.00},
    {"id_insumo": "INS-071", "nome": "Pepino", "categoria_insumo": "Vegetais", "unidade_compra": "kg", "preco_unitario": 6.00},
    {"id_insumo": "INS-072", "nome": "Azeitona", "categoria_insumo": "Vegetais", "unidade_compra": "kg", "preco_unitario": 12.00},
    {"id_insumo": "INS-073", "nome": "Frutas Variadas", "categoria_insumo": "Vegetais", "unidade_compra": "kg", "preco_unitario": 8.00},
    {"id_insumo": "INS-074", "nome": "Legumes Variados", "categoria_insumo": "Vegetais", "unidade_compra": "kg", "preco_unitario": 7.00},
    {"id_insumo": "INS-075", "nome": "Arroz Branco", "categoria_insumo": "Grãos", "unidade_compra": "kg", "preco_unitario": 6.00},
    {"id_insumo": "INS-076", "nome": "Farofa", "categoria_insumo": "Farináceos", "unidade_compra": "kg", "preco_unitario": 5.00},
    {"id_insumo": "INS-077", "nome": "Purê de Batata", "categoria_insumo": "Farináceos", "unidade_compra": "kg", "preco_unitario": 4.00},
    {"id_insumo": "INS-078", "nome": "Cigarro", "categoria_insumo": "Avulsos", "unidade_compra": "un", "preco_unitario": 10.00},
    {"id_insumo": "INS-079", "nome": "Cachaça", "categoria_insumo": "Bebidas", "unidade_compra": "L", "preco_unitario": 30.00},
    {"id_insumo": "INS-080", "nome": "Rum", "categoria_insumo": "Bebidas", "unidade_compra": "L", "preco_unitario": 40.00},
    {"id_insumo": "INS-081", "nome": "Tequila", "categoria_insumo": "Bebidas", "unidade_compra": "L", "preco_unitario": 50.00},
    {"id_insumo": "INS-082", "nome": "Gin", "categoria_insumo": "Bebidas", "unidade_compra": "L", "preco_unitario": 48.00},
    {"id_insumo": "INS-083", "nome": "Vodka", "categoria_insumo": "Bebidas", "unidade_compra": "L", "preco_unitario": 45.00},
    {"id_insumo": "INS-084", "nome": "Limão", "categoria_insumo": "Vegetais", "unidade_compra": "kg", "preco_unitario": 5.00},
    {"id_insumo": "INS-085", "nome": "Hortelã", "categoria_insumo": "Vegetais", "unidade_compra": "kg", "preco_unitario": 15.00},
    {"id_insumo": "INS-086", "nome": "Licor de Laranja", "categoria_insumo": "Bebidas", "unidade_compra": "L", "preco_unitario": 60.00},
    {"id_insumo": "INS-087", "nome": "Suco de Cranberry", "categoria_insumo": "Bebidas", "unidade_compra": "L", "preco_unitario": 12.00},
    {"id_insumo": "INS-088", "nome": "Água Tônica", "categoria_insumo": "Bebidas", "unidade_compra": "L", "preco_unitario": 5.00},
    {"id_insumo": "INS-089", "nome": "Açúcar", "categoria_insumo": "Temperos", "unidade_compra": "kg", "preco_unitario": 3.00},
    {"id_insumo": "INS-090", "nome": "Gelo", "categoria_insumo": "Bebidas", "unidade_compra": "kg", "preco_unitario": 2.00},
    {"id_insumo": "INS-091", "nome": "Chiclete", "categoria_insumo": "Avulsos", "unidade_compra": "un", "preco_unitario": 1.00},
    {"id_insumo": "INS-092", "nome": "Bala", "categoria_insumo": "Avulsos", "unidade_compra": "un", "preco_unitario": 0.50},
    {"id_insumo": "INS-093", "nome": "Amendoim", "categoria_insumo": "Avulsos", "unidade_compra": "kg", "preco_unitario": 8.00},
]