from sqlalchemy import text
from utils.db import executar


SCHEMA = {
    "produtos": """
        cod_prod TEXT PRIMARY KEY,
        nome TEXT,
        descricao TEXT,
        tipo TEXT,
        categoria TEXT,
        p_venda DOUBLE PRECISION,
        p_custo DOUBLE PRECISION,
        margem DOUBLE PRECISION,
        tipo_venda TEXT,
        insumo_direto TEXT,
        marcador_cozinha BOOLEAN
    """,
    "insumos": """
        id_insumo TEXT PRIMARY KEY,
        nome TEXT,
        categoria_insumo TEXT,
        unidade_compra TEXT,
        preco_unitario DOUBLE PRECISION
    """,
    "ficha_tecnica": """
        cod_prod TEXT,
        id_insumo TEXT,
        quantidade DOUBLE PRECISION,
        unidade_ficha TEXT
    """,
    "mesas": """
        id_mesa TEXT,
        status TEXT,
        garcom TEXT,
        qtd_clientes INTEGER,
        aberto_em TEXT,
        fechado_em TEXT,
        valor_pedidos DOUBLE PRECISION,
        valor_total DOUBLE PRECISION,
        valor_com_desconto DOUBLE PRECISION,
        desconto_valor DOUBLE PRECISION,
        valor_10 DOUBLE PRECISION,
        ticket_medio DOUBLE PRECISION,
        cover DOUBLE PRECISION,
        incluir_10 BOOLEAN,
        id_venda_caixa TEXT
    """,
    "pedidos": """
        id_pedido TEXT,
        id_item INTEGER,
        cod_item TEXT,
        id_mesa TEXT,
        cod_prod TEXT,
        nome_prod TEXT,
        quantidade INTEGER,
        preco_unitario DOUBLE PRECISION,
        preco_final DOUBLE PRECISION,
        desconto_tipo TEXT,
        desconto_valor DOUBLE PRECISION,
        subtotal DOUBLE PRECISION,
        valor_com_desconto DOUBLE PRECISION,
        observacao TEXT,
        criado_em TEXT,
        status TEXT,
        categoria TEXT,
        tipo_venda TEXT,
        item_individual TEXT,
        origem_venda TEXT,
        taxa_entrega DOUBLE PRECISION,
        taxa_embalagem DOUBLE PRECISION,
        id_cliente TEXT,
        metodo_pagamento TEXT
    """,
    "clientes": """
        id_cliente TEXT PRIMARY KEY,
        nome_cliente TEXT,
        telefone_principal TEXT,
        telefone_secundario TEXT,
        email TEXT,
        cep TEXT,
        logradouro TEXT,
        numero TEXT,
        complemento TEXT,
        bairro TEXT,
        cidade TEXT,
        estado TEXT,
        referencia TEXT,
        data_cadastro TEXT,
        ativo BOOLEAN,
        latitude TEXT,
        longitude TEXT
    """,
    "funcionarios": """
        id_funcionario TEXT PRIMARY KEY,
        nome TEXT,
        cargo TEXT,
        telefone TEXT,
        email TEXT,
        endereco TEXT,
        valor_dia DOUBLE PRECISION,
        ativo BOOLEAN,
        login TEXT,
        senha_hash TEXT,
        nivel_acesso TEXT,
        fixo BOOLEAN
    """,
    "movimentacoes": """
        id_movimentacao TEXT PRIMARY KEY,
        tipo TEXT,
        id_insumo TEXT,
        quantidade DOUBLE PRECISION,
        unidade TEXT,
        data_movimentacao TEXT,
        preco_unitario DOUBLE PRECISION,
        fornecedor TEXT,
        nota_fiscal TEXT,
        data_validade TEXT,
        id_pedido TEXT,
        cod_item TEXT,
        cod_prod TEXT,
        motivo TEXT,
        usuario TEXT,
        observacao TEXT
    """,
    "delivery": """
        id_pedido TEXT PRIMARY KEY,
        id_cliente TEXT,
        nome_cliente TEXT,
        telefone TEXT,
        endereco TEXT,
        referencia TEXT,
        itens_resumo TEXT,
        valor_total DOUBLE PRECISION,
        taxa_entrega DOUBLE PRECISION,
        criado_em TEXT,
        pronto_em TEXT,
        saiu_entrega_em TEXT,
        chegou_cliente_em TEXT,
        entregue_em TEXT,
        motoboy TEXT,
        status_entrega TEXT,
        latitude TEXT,
        longitude TEXT
    """,
    "agendamentos": """
        id_agendamento TEXT PRIMARY KEY,
        descricao TEXT,
        valor DOUBLE PRECISION,
        data_vencimento TEXT,
        categoria TEXT,
        fornecedor TEXT,
        metodo_pagamento TEXT,
        recorrente BOOLEAN,
        periodicidade TEXT,
        status TEXT,
        data_pagamento TEXT,
        observacao TEXT
    """,
    "compras": """
        id_compra TEXT,
        id_insumo TEXT,
        data_compra TEXT,
        data_validade TEXT,
        quantidade DOUBLE PRECISION,
        unidade TEXT,
        preco_unitario DOUBLE PRECISION,
        valor_total DOUBLE PRECISION,
        fornecedor TEXT,
        nota_fiscal TEXT
    """,
    "estoque": """
        id_insumo TEXT,
        nome_insumo TEXT,
        unidade TEXT,
        estoque DOUBLE PRECISION,
        inventario DOUBLE PRECISION,
        diferenca DOUBLE PRECISION,
        a_vencer_7d DOUBLE PRECISION,
        a_vencer_30d DOUBLE PRECISION,
        ultima_compra TEXT,
        ultimo_inventario TEXT
    """,
    "estoque_baixas": """
        id_baixa TEXT,
        id_pedido TEXT,
        cod_item TEXT,
        cod_prod TEXT,
        id_insumo TEXT,
        quantidade DOUBLE PRECISION,
        unidade TEXT,
        data_baixa TEXT,
        observacao TEXT
    """,
    "estoque_inventario": """
        id_inventario TEXT,
        id_insumo TEXT,
        data_inventario TEXT,
        quantidade_real DOUBLE PRECISION,
        quantidade_virtual DOUBLE PRECISION,
        diferenca DOUBLE PRECISION,
        observacao TEXT,
        usuario TEXT
    """,
    "historico_pedidos": """
        id_pedido TEXT,
        id_item INTEGER,
        cod_item TEXT,
        id_mesa TEXT,
        cod_prod TEXT,
        nome_prod TEXT,
        quantidade INTEGER,
        preco_unitario DOUBLE PRECISION,
        preco_final DOUBLE PRECISION,
        desconto_tipo TEXT,
        desconto_valor DOUBLE PRECISION,
        subtotal DOUBLE PRECISION,
        valor_com_desconto DOUBLE PRECISION,
        observacao TEXT,
        criado_em TEXT,
        data_fechamento TEXT,
        fechado_em TEXT,
        status TEXT,
        categoria TEXT,
        tipo_venda TEXT,
        item_individual TEXT,
        origem_venda TEXT,
        taxa_entrega DOUBLE PRECISION,
        taxa_embalagem DOUBLE PRECISION,
        id_cliente TEXT,
        metodo_pagamento TEXT
    """,
    "historico_mesas": """
        id_mesa TEXT,
        garcom TEXT,
        qtd_clientes INTEGER,
        aberto_em TEXT,
        fechado_em TEXT,
        valor_pedidos DOUBLE PRECISION,
        valor_total DOUBLE PRECISION,
        valor_com_desconto DOUBLE PRECISION,
        desconto_valor DOUBLE PRECISION,
        valor_10 DOUBLE PRECISION,
        ticket_medio DOUBLE PRECISION,
        cover DOUBLE PRECISION,
        incluir_10 BOOLEAN
    """,
    "historico_caixa": "dados JSONB",
    "historico_estoque": "dados JSONB",
    "historico_baixas": "dados JSONB",
    "historico_inventario": "dados JSONB",
    "historico_nao_baixados": "dados JSONB",
    "historico_compras": "dados JSONB",
    "caixa": "dados JSONB",
    "config": "dados JSONB",
}


def criar_schema():
    for nome, colunas in SCHEMA.items():
        executar(f'DROP TABLE IF EXISTS "{nome}"')
        executar(f'CREATE TABLE "{nome}" ({colunas})')
        print(f"Tabela criada: {nome}")


if __name__ == "__main__":
    criar_schema()
    print("Schema Neon criado.")